name: wisata_candi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.4
  sqflite: ^2.3.0                    
  sqflite_common_ffi: ^2.3.0         
  sqflite_common_ffi_web: ^0.4.1     
  path_provider: ^2.1.1              
  path: ^1.8.3      
  image_picker: ^1.2.1                 

  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - images/
